version: "3.8"
services:
  web:
    build:
      context: ./
      target: dev
    command: npm run start:dev
    ports:
      - "8000:8000"
    env_file: ./app/.env
    environment:
      NODE_ENV: development
      DEBUG: node-shoutbox:*