version: "3.8"
services:
  web:
    build:
      context: ./
      target: dev
    volumes:
      - ./app:/app
    command: npm run start:dev
    ports:
      - "8000:8000"
    environment:
      NODE_ENV: development
      DEBUG: node-shoutbox:*